test("GET to /api/v1/status should return 200", async () => {
  const response = await fetch("http://localhost:3000/api/v1/status");
  expect(response.status).toBe(200);

  const responseBody = await response.json();

  const parsedUpdatedAt = new Date(responseBody.updated_at).toISOString();
  expect(responseBody.updated_at).toEqual(parsedUpdatedAt);

  expect(responseBody.dependencies.database.version).toEqual("16.11 (f45eb12)");
  expect(responseBody.dependencies.database.max_connections).toEqual(901);
  expect(responseBody.dependencies.database.opened_connections).toEqual({
    RowCtor: null,
    _parsers: [null],
    _prebuiltEmptyResultObject: { count: null },
    _types: {
      _types: {
        arrayParser: {},
        builtins: {
          ABSTIME: 702,
          ACLITEM: 1033,
          BIT: 1560,
          BOOL: 16,
          BPCHAR: 1042,
          BYTEA: 17,
          CHAR: 18,
          CID: 29,
          CIDR: 650,
          CIRCLE: 718,
          DATE: 1082,
          FLOAT4: 700,
          FLOAT8: 701,
          GTSVECTOR: 3642,
          INET: 869,
          INT2: 21,
          INT4: 23,
          INT8: 20,
          INTERVAL: 1186,
          JSON: 114,
          JSONB: 3802,
          MACADDR: 829,
          MACADDR8: 774,
          MONEY: 790,
          NUMERIC: 1700,
          OID: 26,
          PATH: 602,
          PG_DEPENDENCIES: 3402,
          PG_LSN: 3220,
          PG_NDISTINCT: 3361,
          PG_NODE_TREE: 194,
          POLYGON: 604,
          REFCURSOR: 1790,
          REGCLASS: 2205,
          REGCONFIG: 3734,
          REGDICTIONARY: 3769,
          REGNAMESPACE: 4089,
          REGOPER: 2203,
          REGOPERATOR: 2204,
          REGPROC: 24,
          REGPROCEDURE: 2202,
          REGROLE: 4096,
          REGTYPE: 2206,
          RELTIME: 703,
          SMGR: 210,
          TEXT: 25,
          TID: 27,
          TIME: 1083,
          TIMESTAMP: 1114,
          TIMESTAMPTZ: 1184,
          TIMETZ: 1266,
          TINTERVAL: 704,
          TSQUERY: 3615,
          TSVECTOR: 3614,
          TXID_SNAPSHOT: 2970,
          UUID: 2950,
          VARBIT: 1562,
          VARCHAR: 1043,
          XID: 28,
          XML: 142,
        },
      },
      binary: {},
      text: {},
    },
    command: "SELECT",
    fields: [
      {
        columnID: 0,
        dataTypeID: 23,
        dataTypeModifier: -1,
        dataTypeSize: 4,
        format: "text",
        name: "count",
        tableID: 0,
      },
    ],
    oid: null,
    rowAsArray: false,
    rowCount: 1,
    rows: [{ count: 1 }],
  });
});
